apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    labels:
      app.kubernetes.io/name: nginx
    name: dw-hello-world
    namespace: dweintraub
  spec:
    rules:
    - host: dw-hello-world.rdcpreview.pd-sandbox.com
      http:
        paths:
        - backend:
            service:
              name: dw-hello-world
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - hostname: ab178cbba6cb940898380ceb9aee30d6-abbe1b62e89064f1.elb.us-west-2.amazonaws.com
kind: List
